spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gshmd.vip?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&connectTimeout=10000&socketTimeout=300000
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      connection-max-lifetime: 600000

  thymeleaf:
    cache: false

mybatis:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 300

server:
  port: 8080

# ????
logging:
  level:
    com.example.viewer.mapper: debug  # ????? Mapper SQL
    org.mybatis: debug                  # ?? MyBatis ????
    com.zaxxer.hikari: debug

